modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Asbestosstar"
description='''
CrashDetector tutorial extension.

This mod demonstrates how to create a normal NeoForge mod JAR that also works as a CrashDetector extension.

CrashDetector discovers the extension through the JAR manifest entry:

ExtencionCrashDetector: com.asbestosstar.crashdetector_tutorial_extention_english.TutorialExtention
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
